version: "3.7"
networks:
  fdb-net:

volumes:
  mqtt:
  node-red:
  flogo:

services:
  node-red:
    container_name: node-red
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/:/data/
      - ./dashboard/logo.svg:/usr/src/node-red/node_modules/@node-red/editor-client/public/red/images/node-red.svg
      - ./dashboard/red.js:/usr/src/node-red/node_modules/@node-red/editor-client/public/red/red.js
      - ./dashboard/test.txt:/usr/src/node-red/node_modules/@node-red/editor-client/public/red/test.txt
      - ./dashboard/favicon.ico:/usr/src/node-red/node_modules/@node-red/editor-client/public/favicon.ico
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - fdb-net
  
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt:/mosquitto/data
    networks:
      - fdb-net
  
